params:
  seed: ${...seed}
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    # name: vit_actor_critic
    separate: False
    
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    
    mlp:
      units: [256, 128, 64]
      # [256, 128, 64][4096, 2048, 1024, 512, 256]
      activation: elu

      embed_dim: 256

      # other_input: 15
      # embed_dim_1: 128
      # embed_dim_2: 64

      # hidden_dim: 512
      # num_heads: 2
      # num_layers: 5
      # patch_size: 8
      # num_channels: 3
      # num_patches: 256
      # num_classes: 7
      # dropout: 0.2

      imageWidth: ${task.env.imageWidth}
      imageHeight: ${task.env.imageHeight}

      d2rl: False
      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    name: ${resolve_default:FrankaPIHTaskInsert___testold,${....experiment}}
    full_experiment_name: ${.name}
    env_name: rlgpu
    multi_gpu: ${....multi_gpu}
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 5e-4
    lr_schedule: adaptive
    schedule_type: standard
    kl_threshold: 0.008
    score_to_win: 10000
    max_epochs: ${resolve_default:30000,${....max_iterations}}
    save_best_after: 200
    save_frequency: 100
    print_stats: True
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 32
    # minibatch_size: 16384
    minibatch_size: 2048
    mini_epochs: 5
    critic_coef: 4
    clip_value: True
    seq_len: 4
    bounds_loss_coef: 0.0001
